---
# Ansible Galaxy requirements for Server Helper
# Install with: ansible-galaxy install -r requirements.yml

collections:
  # Docker collection for container management
  - name: community.docker
    version: ">=3.4.0"

  # General community modules
  - name: community.general
    version: ">=8.0.0"

  # Crypto modules for certificate handling
  - name: community.crypto
    version: ">=2.0.0"

  # PostgreSQL modules (for Authentik)
  - name: community.postgresql
    version: ">=3.0.0"

  # Ansible POSIX collection
  - name: ansible.posix
    version: ">=1.5.0"

# Note: Roles are included in this repository under roles/
# No external role dependencies required
