---
# =============================================================================
# Server Helper v0.4.0 — Inventory Example Inventory
# =============================================================================
# Copy to hosts.yml and customize for your environment.
# See docs/wiki/03-configuration.md for details.

all:
  children:
    # Control node — runs management stacks (Traefik, Grafana, etc.)
    control:
      hosts:
        control-node:
          ansible_host: 192.168.1.10
          ansible_user: admin

    # Target nodes — run lightweight agents (Netdata, Promtail, etc.)
    targets:
      hosts:
        server-01:
          ansible_host: 192.168.1.11
          ansible_user: admin

        server-02:
          ansible_host: 192.168.1.12
          ansible_user: admin

        # LXC container example — skip flags auto-detected in pre-flight
        lxc-container:
          ansible_host: 192.168.1.20
          ansible_user: admin
          lvm_skip: true
          swap_skip: true
          qemu_agent_skip: true
