# Server Helper Inventory Example
# ================================
# Copy this file to hosts.yml and customize for your environment.
# The setup.sh script will generate this file automatically.
#
# Usage: cp inventory/hosts.example.yml inventory/hosts.yml

---
all:
  hosts:
    # Control Node (this machine - runs centralized services)
    control:
      ansible_host: 192.168.1.10
      ansible_user: ansible
      ansible_become: yes
      ansible_python_interpreter: /usr/bin/python3
      ansible_connection: local  # Use local connection for control node

    # Target Nodes (managed servers)
    server-01:
      ansible_host: 192.168.1.101
      ansible_user: ansible
      ansible_become: yes
      ansible_python_interpreter: /usr/bin/python3
      # Optional: custom hostname for dashboards
      hostname: "web-server"

    server-02:
      ansible_host: 192.168.1.102
      ansible_user: ansible
      ansible_become: yes
      ansible_python_interpreter: /usr/bin/python3
      # Optional: non-standard SSH port
      ansible_port: 2222

    # Example: LXC Container (skip LVM and swap)
    lxc-container:
      ansible_host: 192.168.1.150
      ansible_user: ansible
      ansible_become: yes
      ansible_python_interpreter: /usr/bin/python3
      # Skip operations not supported in LXC
      lvm_skip: true
      swap_skip: true
      qemu_agent_skip: true

  children:
    # Group: Control Node (centralized services)
    control_nodes:
      hosts:
        control:

    # Group: Target Nodes (managed servers)
    targets:
      hosts:
        server-01:
        server-02:
        lxc-container:

    # Group: Physical/VM servers (full features)
    servers:
      hosts:
        server-01:
        server-02:

    # Group: LXC containers (limited features)
    containers:
      hosts:
        lxc-container:

  vars:
    # Global SSH settings
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
