{
 "title": "Docker Containers",
 "tags": [
  "server-helper",
  "docker"
 ],
 "refresh": "30s",
 "panels": [
  {
   "title": "Container Status",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "netdata_docker_engine_engine_daemon_container_states_containers_average",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "netdata_cgroup_cpu_limit_percentage_average",
     "legendFormat": "{{chart}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "netdata_cgroup_mem_usage_MiB_average",
     "legendFormat": "{{chart}}"
    }
   ]
  }
 ]
}